# Site settings
title: Sebastian Blei
subtitle: Sebastian Blei
author: Sebastian Blei
email: s@blei.in
description: > # this means to ignore newlines until "baseurl:"
  Informationen von und über Sebastian Blei.
  Blog, Kontakt, Person.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sebastianblei.com" # the base hostname & protocol for your site
twitter_username: iamblei
github_username:  iamsebastian

# Directories
deploy: _site

# ----------------------- #
#      Main Configs       #
# ----------------------- #

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%e %B %Y"
# date_format: "%e. %B %Y"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: mail@sebastianblei.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
plugins: _plugins
code_dir: downloads/code

category_dir: blog/categories
category_title_prefix: 'Kategorie: '
category_dir: 'kategorien'

markdown: rdiscount
safe: false
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 5                             # Posts per page on the blog index
paginate_path: 'blog/seite/:num'        #
recent_posts: 2                         # Posts in the sidebar Recent Posts section

timezone: 'DE'                          # timezone http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
titlecase: false                        # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html]
